apps/api/urls.py
# -*- coding:utf-8 -*-
__author__ = 'zhengjiali'
__date__ = '2018/2/26 下午10:33'
from django.conf.urls import url

from .views import *
from .test_views import CaseTestView

urlpatterns = [
    url(r'^apis$', ApiQueryView.as_view(),name="query" ),
    url(r'^apiList/$',api_list,name="api_list"),
    # url(r'^(?P<api_id>\w+)/addCase$',CaseNewView.as_view(),name="addcase"),
    #dean 修改接口用例界面配置2018-05-07 -- start --
    url(r'(?P<api_id>\w+)/cases/$',get_testcases),
    url(r'^caselist$',get_caseslist),
    #dean 修改接口用例界面配置2018-05-07 -- end --
    url(r'^cases$',data_list),
    url(r'^(?P<api_id>\w+)$',ApiView.as_view(),name="api"),
    url(r'^addApi/$',ApiNewView.as_view(),name="addapi"),
    url(r'(?P<api_id>\w+)/edit/',edit_api,name='edit_api'),
    url(r'^cases/(?P<case_id>\w+)/',get_case),
    url(r'^case/copy/(?P<case_id>\w+)$',CaseCopyView.as_view()), #复制用例
    url(r'^case/delete/(?P<case_id>\w+)$',case_delete),#删除用例
    url(r'^casetest/(?P<case_id>\w+)/$',CaseTestView.as_view(),name="doTest"),
    url(r'^(?P<api_id>\w+)/addTestCase$',CaseNewView.as_view(),name="addTestCase"),
    url(r'^(?P<api_id>\w+)/initTestCase$',InitCaseView.as_view(),name="initTestCase"),
    url(r'^addCase/$',CaseNewView.as_view(),name="addCase"),
    url(r'^tags/$',get_tags),
    url(r'^cases/query$',CaseQueryView.as_view(),name="case_query"),
]

easyapi/urls.py
from django.conf.urls import url,include
# from django.contrib import admin
from users.views import LoginView,LogoutView
from api.views import get_projects,get_users,get_env,upload_file
from task.report import get_tasks,task_query,get_report,get_cases,get_result
from task.statistics import CountView
import xadmin

urlpatterns = [
    url(r'^admin/', xadmin.site.urls),
    url(r'^api/',include("api.urls",namespace='api')),
    url(r'^login/$',LoginView.as_view(),name="login"),
    url(r'^logout/$',LogoutView.as_view(),name="logout"),
    url(r'^projs/$',get_projects),
    url(r'^plan/',include("task.urls",namespace='plan')),
    url(r'^users/$',get_users),
    url(r'^env/$',get_env),
    url(r'^task/$',get_tasks),
    url(r'^task/query$',task_query),
    url(r'^task/(?P<task_id>\w+)/report$',get_report),
    url(r'^task/(?P<task_id>\w+)/cases$',get_cases),
    url(r'^task/(?P<task_id>\w+)/cases/(?P<case_id>\w+)$',get_result),
    url(r'^statistics/$',CountView.as_view()),
    url(r'^tcredit/',include("tcredit.urls",namespace='tcredit')),
    url(r'^uploadFile$',upload_file),

]

# from django.conf.urls import url,include
# from rest_framework import routers
# from .viewsets import TagViewset,UserViewset,ApiConfigViewset
#
# router = routers.DefaultRouter()
#
# router.register(r'tags',TagViewset)
# router.register(r'apis',ApiConfigViewset)
# router.register(r'users',UserViewset)
#
# urlpatterns = [
#     url(r'^',include(router.urls)),
#     url(r'^api/',include('rest_framework.urls',namespace='rest_framework')),
# ]

templates/api_add.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta name=”renderer” content=”webkit” />
<meta name="viewport" content="width=device-width">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="keywords" content="">
<meta name="Description" content="Dean">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="X-UA-Compatible" content="IE=8; IE=9; IE=10" />
<meta charset="utf-8">
<title>Voldemort</title>
{% load staticfiles %}
<link href="/static/Font-Awesome-master4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="/static/bootstrap3.3.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/static/bootstrap3.3.0/css/bootstrapValidator.min.css" rel="stylesheet" type="text/css" />
<link href="/static/dist/css/bootstrap-select.css" rel="stylesheet" type="text/css" />
<link href="/static/src/css/common.css" rel="stylesheet" type="text/css" />
<link href="/static/src/css/api_add.css" rel="stylesheet" type="text/css" />
</head>
<body>
 <div class="container_all">
  <nav class="navbar navbar-default navbar-fixed-top">
   <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand logo">Voldemort</a>     
    </div> 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
          <ul class="nav navbar-nav menu_list" id="menu_area"></ul>        
          <p class="navbar-text navbar-right"><a href="javascript:void(0)" id="logoff"><i class="fa fa-sign-out fa-lg"></i></a></p>
          <p class="navbar-text navbar-right">{{user.username}}</p>
    </div>
   </div>
  </nav>
  <div class="content">
    <div class="loading" style="display:none;">
      <div class="loading_message">
        <i class="fa fa-spinner fa-pulse fa-4x fa-fw"></i>
      </div>
    </div>
     <div class="main">
       <div class="main_content" >
        <div class="add_table"> 
          <div class="add_table_title"><span>新增接口</span></div> 
          <div class="add_table_content">
            <form id="add_table_form">
              <div class="form-group">
                <label for="exampleInputEmail1">API名称<i class="fa fa-asterisk" aria-hidden="true"></i></label>
                <input type="text" class="form-control" id="t_api_name" name="name" placeholder="请输入名称" maxlength="40">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">请求路径<i class="fa fa-asterisk" aria-hidden="true"></i></label>
                <input type="text" class="form-control" id="t_api_url" name="path" placeholder="请输入url" maxlength="1000">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">请求方式<i class="fa fa-asterisk" aria-hidden="true"></i></label>
                <select class="form-control selectpicker" name="method">
                  <option>post</option>
                  <option>get</option>
                </select>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">所属项目<i class="fa fa-asterisk" aria-hidden="true"></i></label>
                <select class="form-control selectpicker" data-live-search="true" name="project">
                  {% for proj in projs %}
                    <option value="{{proj.id}}">{{ proj.name}}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">API描述</label>
                <textarea class="form-control" rows="3" name="description"></textarea>
              </div>
              <button type="button" onClick="api_add();" class="btn btn-default" id="api_add_btn">确认提交 <i class="fa fa-hand-o-right" aria-hidden="true"></i></button>
            </form>
          </div>        
          </div>
       </div>
     </div>
   </div>
  <footer class="bottom">
    <div class="container">
      <p>Designed and built by Testing team.</p>
    </div>
  </footer>
 </div> 
</div>
 <!-- 消息提示 -->
<div class="alert alert-danger collapse fade in error_message" id="confirm_error" style="display: none;">
  <button  type="button" class="close" aria-label="Close" onclick="close_pop_error()">
    &times;
  </button>
  <strong id="error_mess"></strong>
</div>
<div class="alert alert-success collapse fade in sucess_message" id="confirm_sucess" style="display: none;">
  <button  type="button" class="close" aria-label="Close" onclick="close_pop_success()">
    &times;
  </button>
  <strong id="sucess_mess"></strong>
</div>
<script src="/static/dist/js/jquery2.min.js"></script>
<script src="/static/bootstrap3.3.0/js/bootstrap.min.js" charset="utf-8"></script>
<script src="/static/bootstrap3.3.0/js/bootstrapValidator.min.js" charset="utf-8"></script>
<script src="/static/dist/js/bootstrap-select.js" charset="UTF-8"></script>
<script src="/static/src/js/common.js"></script>
<script src="/static/src/js/api_add.js"></script>
<script type="text/javascript">
 $(function(){
  // 初始化界面
  creatmenu();
  menu_current(0);
  $("#add_table_form").bootstrapValidator({  
          message:'',  
          feedbackIcons:{
            valid:'glyphicon glyphicon-ok',
            invalid:'glyphicon glyphicon-remove',
            validating:'glyphicon glyphicon-refresh'
          },
          fields:{
            name:{     //用户名校验
              message:'',
              validators:{
                notEmpty:{
                  message:'API名称不能为空'
                         },
                  regexp: {
                            regexp: /^[^&]+$/,
                            message: '不可以输入&连接符'
                        }
                         }
                     },
              path:{     //密码校验
              message:'',
              validators:{
                notEmpty:{
                  message:'请求路径不能为空'
                         },
                  regexp: {
                            regexp: /^[^&]+$/,
                            message: '不可以输入&连接符'
                        }
                         }
                         }                   
                     }        
        });
 });
</script>
</body>
</html>

templates/api_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta name=”renderer” content=”webkit” />
<meta name="viewport" content="width=device-width">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="keywords" content="">
<meta name="Description" content="Dean">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="X-UA-Compatible" content="IE=8; IE=9; IE=10" />
<meta charset="utf-8">
<title>Voldemort</title>
{% load staticfiles %}
<link href="/static/Font-Awesome-master4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="/static/bootstrap3.3.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/static/bootstrap3.3.0/css/bootstrapValidator.min.css" rel="stylesheet" type="text/css" />
<link href="/static/dist/css/bootstrap-select.css" rel="stylesheet" type="text/css" />
<link href="/static/src/css/common.css" rel="stylesheet" type="text/css" />
<link href="/static/src/css/api_add.css" rel="stylesheet" type="text/css" />
</head>
<style type="text/css">
</style>
<script type="text/javascript">
</script>
</head>
<body>
 <div class="container_all">
  <nav class="navbar navbar-default navbar-fixed-top">
   <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand logo">Voldemort</a>     
    </div> 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
          <ul class="nav navbar-nav menu_list" id="menu_area"></ul>        
          <p class="navbar-text navbar-right"><a href="javascript:void(0)" id="logoff"><i class="fa fa-sign-out fa-lg"></i></a></p>
          <p class="navbar-text navbar-right">{{ request.user.username }}</p>
    </div>
   </div>
  </nav>
  <div class="content">
    <div class="loading" style="display:none;">
      <div class="loading_message">
        <i class="fa fa-spinner fa-pulse fa-4x fa-fw"></i>
      </div>
    </div>
     <div class="main">
       <div class="main_content" >
        <div class="add_table"> 
          <div class="add_table_title"><span>编辑接口</span></div> 
          <div class="add_table_content">
            <form id="edit_table_form">
              <div class="form-group">
                <input type="text" id="t_api_id" name="api_id" value="{{ api.id }}" style="display: none;">
                <label for="exampleInputEmail1">API名称<i class="fa fa-asterisk" aria-hidden="true"></i></label>
                <input type="text" class="form-control" id="t_api_name" name="name"  maxlength="40" value = "{{api.name}}">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">请求路径<i class="fa fa-asterisk" aria-hidden="true"></i></label>
                <input type="text" class="form-control" id="t_api_url" name="path" value="{{api.path}}" maxlength="1000">
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">请求方式<i class="fa fa-asterisk" aria-hidden="true"></i></label>
                <select class="form-control" name="method">
                  <option {% ifequal api.method 'post' %}selected="selected"{% endifequal %}>post</option>
                  <option {% ifequal api.method 'get' %}selected="selected"{% endifequal %}>get</option>
                </select>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">所属项目<i class="fa fa-asterisk" aria-hidden="true"></i></label>
                <select class="form-control" name="project">
                   {% for proj in projs %}
                    <option value="{{proj.id}}" {% ifequal api.proj proj %}selected="selected"{% endifequal %}>{{ proj.name}}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">API描述</label>
                <textarea class="form-control" rows="3" name="description">{{api.description}}</textarea>
              </div>
              <button type="button" class="btn btn-default refresh_page">取消 </button>
              <button type="button" onClick="api_edit();" class="btn btn-default" id="api_add_btn">确认提交 <i class="fa fa-hand-o-right" aria-hidden="true"></i></button>
            </form>
          </div>        
          </div>
       </div>
     </div>
   </div>
  <footer class="bottom">
    <div class="container">
      <p>Designed and built by Testing team.</p>
    </div>
  </footer>
 </div>
 <!-- 消息提示 -->
<div class="alert alert-danger collapse fade in error_message" id="confirm_error" style="display: none;">
  <button  type="button" class="close" aria-label="Close" onclick="close_pop_error()">
    &times;
  </button>
  <strong id="error_mess"></strong>
</div>
<div class="alert alert-success collapse fade in sucess_message" id="confirm_sucess" style="display: none;">
  <button  type="button" class="close" aria-label="Close" onclick="close_pop_success()">
    &times;
  </button>
  <strong id="sucess_mess"></strong>
</div>
</div>
<script src="/static/dist/js/jquery2.min.js"></script>
<script src="/static/bootstrap3.3.0/js/bootstrap.min.js" charset="utf-8"></script>
<script src="/static/bootstrap3.3.0/js/bootstrapValidator.min.js" charset="utf-8"></script>
<script src="/static/dist/js/bootstrap-select.js" charset="UTF-8"></script>
<script src="/static/src/js/common.js"></script>
<script src="/static/src/js/api_add.js"></script>
<script type="text/javascript">
 $(function(){
  // 初始化界面
  creatmenu();
  menu_current(0);
  $("#edit_table_form").bootstrapValidator({  
          message:'',  
          feedbackIcons:{
            valid:'glyphicon glyphicon-ok',
            invalid:'glyphicon glyphicon-remove',
            validating:'glyphicon glyphicon-refresh'
          },
          fields:{
            name:{     //用户名校验
              message:'',
              validators:{
                notEmpty:{
                  message:'API名称不能为空'
                         },
                  regexp: {
                            regexp: /^[^&]+$/,
                            message: '不可以输入&连接符'
                        }
                         }
                     },
              path:{     //密码校验
              message:'',
              validators:{
                notEmpty:{
                  message:'请求路径不能为空'
                         },
                  regexp: {
                            regexp: /^[^&]+$/,
                            message: '不可以输入&连接符'
                        }
                         }
                         }                   
                     }        
        });
 });
</script>
</body>
</html>

templates/api_list.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta name=”renderer” content=”webkit” />
<meta name="viewport" content="width=device-width">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="keywords" content="">
<meta name="Description" content="Dean">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="X-UA-Compatible" content="IE=8; IE=9; IE=10" />
<meta charset="utf-8">
<title>Voldemort</title>
{% load staticfiles %}
<link href="/static/Font-Awesome-master4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="/static/bootstrap3.3.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/static/dist/css/bootstrap-select.css" rel="stylesheet" type="text/css" />
<link href="/static/src/css/common.css" rel="stylesheet" type="text/css" />
<link href="/static/src/css/api_list.css" rel="stylesheet" type="text/css" />

</head>
<style type="text/css">
</style>
<script type="text/javascript">
</script>
</head>
<body>
 <div class="container_all">
  <nav class="navbar navbar-default navbar-fixed-top">
   <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand logo">Voldemort</a>     
    </div> 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
          <ul class="nav navbar-nav menu_list" id="menu_area"></ul>        
          <p class="navbar-text navbar-right"><a href="javascript:void(0)" id="logoff"><i class="fa fa-sign-out fa-lg"></i></a></p>
          <p class="navbar-text navbar-right">{{ request.user.username }}</p>
    </div>
   </div>
  </nav>
  <div class="content">
    <div class="loading" style="display:none;">
      <div class="loading_message">
        <i class="fa fa-spinner fa-pulse fa-4x fa-fw"></i>
      </div>
    </div>
     <div class="main">
      <div class="main_search">
        <div class="main_search_content">
            <ul class="list-inline">
            <li class="pull-left">
                <button type="button" class="btn btn-default" onclick="apiAdd()"><i class="fa fa-plus-square-o" aria-hidden="true"></i>&nbsp; 新增接口</button>
            </li>
            <li>
              <div class="form-inline">
                    <input type="file" name="myfile" id="file" class="form-control" />
                    <input type="submit" class="btn btn-primary" value="导入"/ onclick="upload()">
              </div>
            </li>
             <li class="pull-right">
                <form class="form-inline">
                  <div class="form-group">
                  <label for="c_main_page_top_left_checkbox_label1">所属项目</label>
                      <select class="form-control selectpicker select_api" data-live-search="true" id="keytypes">
                        <option value="">请选择</option>
                        {% for proj in projs %}
                        <option value="{{proj.id}}">{{ proj.name}}</option>
                        {% endfor %}
                      </select>
                  </div>
                  <div class="form-group search">
                    <input type="text" class="form-control search_input" placeholder="请输入接口名称" id="keywords">
                    <span class="input-group-btn">
                  </div>
                  <button class="btn btn-default" type="button" onClick="query(1,10);"><i class="fa fa-search"></i></button>
                </form>
             </li>
           </ul>      
          </div>
         </div>
       <div class="main_content" >
          <div id="center_content_table" class="center_content_table">          
          </div>
          <div class="pagination1">
       <nav style="text-align: center" id="fenye"></nav></div>
       </div>
     </div>
   </div>
  <footer class="bottom">
    <div class="container">
      <p>Designed and built by Testing team.</p>
    </div>
  </footer>
 </div>
</div>
 <!-- 消息提示 -->
<div class="alert alert-danger collapse fade in error_message" id="confirm_error" style="display: none;">
  <button  type="button" class="close" aria-label="Close" onclick="close_pop_error()">
    &times;
  </button>
  <strong id="error_mess"></strong>
</div>
<div class="alert alert-success collapse fade in sucess_message" id="confirm_sucess" style="display: none;">
  <button  type="button" class="close" aria-label="Close" onclick="close_pop_success()">
    &times;
  </button>
  <strong id="sucess_mess"></strong>
</div>
<div class="alert alert-warning collapse fade in sucess_message" id="confirm_warning" style="display: none;">
  <button  type="button" class="close" aria-label="Close" onclick="close_pop_error()" style="padding-top: 5px;">
    &times;
  </button>
  <strong id="warning_mess">确定要删除接口吗？好好想想？</strong>
  <button class="btn" type="button" onclick="plan_delete()">确定</button>
</div>
<script src="/static/dist/js/jquery2.min.js"></script>
<script src="/static/bootstrap3.3.0/js/bootstrap.min.js" charset="utf-8"></script>
<script src="/static/dist/js/bootstrap-select.js" charset="UTF-8"></script>
<script src="/static/dist/js/extendPagination.js"></script>
<script src="/static/src/js/common.js"></script>
<script src="/static/src/js/api_list.js"></script>
<script type="text/javascript">
 $(function(){
  // 初始化界面
  loading(0);
  creatmenu();
  menu_current(0);
  query(1,10);
 });
</script>
</body>
</html>ody>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
<meta name=”renderer” content=”webkit” />
<meta name="viewport" content="width=device-width">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<meta name="keywords" content="">
<meta name="Description" content="Dean">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<meta http-equiv="X-UA-Compatible" content="IE=8; IE=9; IE=10" />
<meta charset="utf-8">
<title>Voldemort</title>
<link href="/static/Font-Awesome-master4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="/static/bootstrap3.3.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/static/src/css/login.css" rel="stylesheet" type="text/css" />
<script src="/static/dist/js/jquery2.min.js"></script>
<script src="/static/bootstrap3.3.0/js/bootstrap.min.js" charset="utf-8"></script>
</head>
<style type="text/css">
.alert{
  width: 100%;
  height: 55px;
  position: fixed;
  top:0px;
  margin-top: 0px !important;

}
</style>
<script type="text/javascript">
   function close_pop(){
    $(".error_message").slideUp();
 } 
</script>
</head>
<body>
 <div id="screen">
  <div class="login">
    <div class="login_main">
      <div class="header">
        <span class="sys_name">Voldemort<strong class="sys_version"> v2.0</strong></span>
      </div>
      <div class="middle">
        <form id="form1">
          <div class="form-group">
            <input type="text" class="form-control login_components" placeholder="请输入username" name="username">      
          </div>
          <div class="form-group">
            <input type="password" class="form-control login_components" placeholder="请输入password" name="password">     
          </div>                    
        </form>
        <button type="button" class="btn btn-default" id="login-button">登陆</button>
      </div>
    </div>
  </div> 
 
<div class="alert alert-danger collapse fade in error_message" id="confirm_error" style="display: none;">
  <button  type="button" class="close" aria-label="Close" onclick="close_pop()">
    &times;
  </button> 
  <strong id="error_mess"></strong>
</div>
<div class="alert alert-success collapse fade in error_message" id="confirm_error" style="display: none;">
  <button  type="button" class="close" aria-label="Close" onclick="close_pop()">
    &times;
  </button> 
  <strong id="error_mess"></strong>
</div>
</div>
<script type="text/javascript">
$('#login-button').click(function(event){
	$.ajax({
    url:'/login/',
    type : "Post",
    async: false,
    data: $("#form1").serialize(),
    dataType: 'json',
    success:function(data)
    {
      var Data = data["msg"];
      var Status = data["status"];
      if (Status==0){
      	window.location.href="{% url 'api:api_list' %}";
      }
      else{
      	$("#error_mess").html(Data);
      $("#confirm_error").slideDown();
      }           
    },
    error:function(data)
    {
      $("#error_mess").html("系统异常！");
      $("#confirm_error").slideDown();
    }
  });
});
$(document).keyup(function(event){
  if(event.keyCode ==13){
    $("#login-button").trigger("click");
  }
});
</script>
</body>
</html>

templates/new_api.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="main_bd">
    <div class="form_wrap">
        <form id="form1" novalidate="novalidate">
            <ul class="form searchbar_list">
               <li class="field_wrap">
                <label class="form_text"><em class="form_required">*</em>api：</label>
                <input type="text" class="field" name="name" value="" maxlength="101">
            </li>
            <li class="field_wrap">
                <label class="form_text"><em class="form_required">*</em>描述：</label>
                <input type="text" class="field" name="description" value="" maxlength="41">
            </li>
            <li class="field_wrap">
                <label class="form_text"><em class="form_required">*</em>url：</label>
                <input type="text" class="field" name="path" value="" maxlength="41">
            </li>
            <li class="field_wrap">
                <label class="form_text"><em class="form_required">*</em>method：</label>
                <select name="method" id="method" class="field">
                    <option value="">请选择</option>
                                        <option value="get">get</option>
                                        <option value="post">post</option>
                                    </select>
            </li>
            <li class="field_wrap">
                <label class="form_text"><em class="form_required">*</em>项目：</label>
                <select name="project" id="project" class="field">
                    <option value="">请选择</option>
                    {% for proj in projs %}
                        <option value="{{ proj.id }}">{{ proj.name }}</option>
                    {% endfor %}
                </select>
            </li>

        </ul>
                <div class="btns">
            <a class="btn btn_cancel" href="/riskData/trics/plan/toQueryPlan" id="btn_cancel">取 消</a>
            <div type="button" class="btn" id="btnSave">确定</div>
        </div>
    </form>
</div>
</div>
<script src="/static/dist/js/jquery2.min.js"></script>
<script>
    $('#btnSave').click(function(event) {

    $.ajax({
        url: "/api/addApi/",
        type: "POST",
        data: $("#form1").serialize(),
        dataType: "json",
        {#beforeSend:function(xhr, settings){#}
        {#    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");#}
        {#},#}
        success: function (data)
        {
            alert(data["msg"]);
        },
        error: function (data) {
            alert("系统异常");
        }
    });
});
</script>
</body>
</html>